"""Shared Pydantic schemas (canonical — used by council, router live smoke, UI)."""

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field



class CouncilScores(BaseModel):
    """One judge's evaluation of one draft (plan v2 §5)."""

    narrative: float = Field(ge=0, le=10, description="Narrative architecture: hook strength, spine, rhythm")
    velocity: float = Field(ge=0, le=10, description="Conversational velocity: punchiness, clarity")
    depth: float = Field(ge=0, le=10, description="Substantive depth: psychology, timelessness")
    slop_purity: float = Field(ge=0, le=10, description="Lexical purity: zero AI tells")
    threshold_met: bool = Field(description="Composite reaches publication bar")
    verdict: Literal["pass", "revise", "reject"]
    required_actions: list[str] = Field(min_length=1, max_length=5)


class IdeaScore(BaseModel):
    """One sampled scoring of a content idea (plan v2 §2.2)."""

    pov: float = Field(ge=0, le=10, description="Point of view: falsifiable contrarian thesis")
    lived_experience: float = Field(ge=0, le=10, description="Grounding in concrete operational reality")
    specificity: float = Field(ge=0, le=10, description="Anecdotal specificity: metrics, dates, dialogue")
    counter_intuitive: float = Field(ge=0, le=10, description="Disruption of standard industry assumptions")
    generic_penalty_applied: bool = Field(description="Concept is a known business cliche; -0.50 composite penalty")
    composite: float = Field(ge=0, le=10)
    rationale: str


class InterviewQuestion(BaseModel):
    """An interrogation question generated by an interviewer persona."""

    persona: str = Field(description="Persona name (e.g. Tim Ferriss, Larry King, Joe Rogan, Barbara Walters)")
    focus: str = Field(description="Focus area: e.g. Tactical mechanics, Bottom line, Counter-intuitive angle")
    question: str = Field(description="The direct probing question posed to the creator")


class TopicBriefing(BaseModel):
    """Executive briefing and interrogation questions for a scored topic."""

    summary: str = Field(description="2-3 sentence executive briefing of the topic and why it matters")
    core_conflict: str = Field(description="The central debate, tension, or trade-off")
    questions: list[InterviewQuestion] = Field(min_length=1, max_length=5)


class TopicBriefRequest(BaseModel):
    title: str = Field(min_length=1)
    url: str | None = None
    body: str | None = None
    topic_tag: str = "General Engineering"


class InterviewResponseItem(BaseModel):
    persona: str
    question: str
    answer: str


class SynthesizeDraftRequest(BaseModel):
    topic_title: str
    topic_summary: str
    responses: list[InterviewResponseItem] = Field(default_factory=list)
    raw_notes: str | None = None
    spike_id: str = "cli-session"


class SynthesizeDraftResponse(BaseModel):
    draft: str
    word_count: int
    spike_id: str


class HumanizeTone(str, Enum):
    PUNCHY_DIRECT = "punchy_direct"
    PRAGMATIC_ARCHITECT = "pragmatic_architect"
    CONVERSATIONAL_PEER = "conversational_peer"


class CommentAngle(str, Enum):
    INSIGHTFUL = "insightful"
    CONTRARIAN = "contrarian"
    QUESTION = "question"


class GenerateCommentRequest(BaseModel):
    post_content: str = Field(min_length=10, description="Raw content of the LinkedIn post being commented on")
    angle: CommentAngle = CommentAngle.INSIGHTFUL
    perspective_text: str | None = None
    humanize: bool = Field(default=True, description="Apply Humanize Transformer polish pass")
    tone: HumanizeTone = Field(default=HumanizeTone.PUNCHY_DIRECT, description="Target human tone")


class CommentRunResponse(BaseModel):
    comment_id: str
    initial_draft: str
    final_comment: str
    iteration: int
    peak_score: float
    verdict: str
    actions: list[str] = Field(default_factory=list)
    judge_scores: dict[str, float] = Field(default_factory=dict)
    judge_critiques: dict[str, str] = Field(default_factory=dict)
    humanized: bool = Field(default=True)
    humanize_tone: str = Field(default="punchy_direct")
    burstiness_score: float = Field(default=0.0)


class CommentHistoryItem(BaseModel):
    id: str
    post_content: str
    angle: str
    perspective_text: str | None = None
    final_comment: str
    iteration_count: int
    peak_score: float
    verdict: str
    humanized: bool = False
    humanize_tone: str | None = None
    burstiness_score: float | None = 0.0
    created_at: str


class CommentHistoryResponse(BaseModel):
    items: list[CommentHistoryItem] = Field(default_factory=list)
    total: int


class ProfileData(BaseModel):
    """Codified author persona, voice profile, and domain invariants."""

    name: str = "Prasad Rane"
    headline: str = "Senior Software & AI Systems Engineer"
    current_focus: str
    technical_domains: list[str] = Field(default_factory=list)
    hard_invariants: list[str] = Field(default_factory=list)
    full_markdown: str = ""


class UpdateProfileRequest(BaseModel):
    """Payload for updating editable profile attributes."""

    current_focus: Optional[str] = None
    technical_domains: Optional[list[str]] = None
    custom_notes: Optional[str] = None


class HumanizeChannel(str, Enum):
    LINKEDIN_COMMENT = "linkedin_comment"
    LINKEDIN_POST = "linkedin_post"
    X_THREAD = "x_thread"
    VIDEO_SCRIPT = "video_script"
    GENERAL = "general"


class HumanizeRequest(BaseModel):
    text: str = Field(..., min_length=10, description="Draft text to humanize")
    channel: HumanizeChannel = Field(default=HumanizeChannel.LINKEDIN_POST)
    tone: HumanizeTone = Field(default=HumanizeTone.PRAGMATIC_ARCHITECT)
    max_sentences: Optional[int] = Field(default=None, description="Optional hard sentence clamp")


class HumanizeResult(BaseModel):
    original_text: str
    humanized_text: str
    channel: HumanizeChannel
    tone: HumanizeTone
    banned_words_purged: list[str] = Field(default_factory=list)
    burstiness_score: float = Field(default=0.0, description="Standard deviation of sentence word counts")
    sentence_count: int = Field(default=0)
    was_modified: bool = Field(default=True)


class DistributeRunRequest(BaseModel):
    anchor_post: str = Field(min_length=10)
    project_slug: Optional[str] = None
    enabled_formats: Optional[list[str]] = None
    humanize: bool = Field(default=True)
    tone: HumanizeTone = Field(default=HumanizeTone.PRAGMATIC_ARCHITECT)




